name: "âœ¨ On push to any branch"

on:
  push:

jobs:
#  build:
#    name: 'ðŸ§ª Build & test Code'
#    uses: ./.github/workflows/build.yaml
#    secrets: inherit

  echo:
    name: echo
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "ey"

#  check-docs:
#    name: "Check documentation"
#    uses: ./.github/workflows/check-documentation.yml
