name: "âœ¨ On push to any branch"

on:
  push:

jobs:
  lint:
    name: ğŸ’„ Code Quality
    uses: ./.github/workflows/lint.yml

  test:
    name: Run tests
    uses: ./.github/workflows/tests.yml

#  build:
#    name: 'ğŸ§ª Build & test Code'
#    uses: ./.github/workflows/build.yaml
#    secrets: inherit

#  check-docs:
#    name: "Check documentation"
#    uses: ./.github/workflows/check-documentation.yml


  todo-check:
    name: ğŸ§ Check TODOs
    uses: ./.github/workflows/todo-check.yml
