name: "âœ¨ On push to main branch"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
#  build:
#    name: 'ğŸ§ª Build & test Code'
#    uses: ./.github/workflows/build.yaml
#    secrets: inherit

  publish-docs:
    name: 'ï¸â€ğŸ“šï¸ Publish Docs'
    uses: ./.github/workflows/docs.yml
