name: ğŸ”– Release please

on:
  workflow_dispatch: #  Enable manual triggers.
  workflow_call: # Enables workflow to be called from another workflow.
    outputs:
      release_created:
        description: "If true, a release PR has been merged"
        value: ${{ jobs.release-please.outputs.release_created }}
      tag_name:
        description: "The release tag. Ex v1.4.0"
        value: ${{ jobs.release-please.outputs.tag_name }}

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: python
          target-branch: main
          package-name: "completor"
          changelog-types: >
            [
              {"type":"build", "section":"ğŸ“¦ Build system","hidden":false},
              {"type":"chore", "section":"ğŸ§¹ Chores","hidden":false},
              {"type":"ci", "section":"ğŸ‘· CI/CD","hidden":false},
              {"type":"docs","section":"ğŸ“ Documentation","hidden":false},
              {"type":"feat","section":"âœ¨ Features","hidden":false},
              {"type":"fix","section":"ğŸ› Bug Fixes","hidden":false},
              {"type":"perf", "section":"âš¡ï¸ Performance","hidden":false},
              {"type":"refactor", "section":"â™»ï¸ Refactor","hidden":false},
              {"type":"revert", "section":"âªï¸ Revert","hidden":false},
              {"type":"style","section":"ğŸ’„ Style","hidden":false},
              {"type":"test", "section":"âœ… Tests","hidden":false}
            ]


    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
